service: bird-san

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'development'}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  check_in:
    handler: handler.check_in
    timeout: 10
    events:
      - http:
          path: /check-in
          method: post
